// All interface text lives here so Russian and Korean can be added later
// (phase 2) by adding strings.ru.js / strings.ko.js without redesigning.
export default {
  siteName: 'TIS Owls Live',
  tagline: 'Challenge | Explore | Connect',
  metaDescription: 'Watch Tashkent International School Owls games live or as replays. Football, basketball and volleyball.',
  skip: 'Skip to content',
  cta: 'Find a game',
  nav: { schedule: 'Live & Schedule', replays: 'Replays', teams: 'Teams', about: 'About' },
  sports: { football: 'Football', basketball: 'Basketball', volleyball: 'Volleyball' },
  levels: { varsity: 'Varsity', jv: 'Junior Varsity' },
  levelsShort: { varsity: 'Varsity', jv: 'JV' },
  filters: { all: 'All', sport: 'Sport', level: 'Level', none: 'No games match these filters.' },
  status: { live: 'Live', scheduled: 'Upcoming', final: 'Final' },
  owls: 'Owls',
  vs: 'vs',
  hero: {
    liveNow: 'Live now',
    nextGame: 'Next game',
    watchLive: 'Watch live',
    gameDetails: 'Game details',
    emptyTitle: 'No games scheduled',
    emptyText: 'The next fixtures will appear here. Meanwhile, catch up on replays.',
    browseReplays: 'Browse replays',
    days: 'days', hours: 'hours', minutes: 'min'
  },
  home: { thisWeek: 'Coming up', latestReplays: 'Latest replays', allSchedule: 'Full schedule', allReplays: 'All replays' },
  schedule: { title: 'Live & Schedule', intro: 'Times are shown in Tashkent time (UTC+5), with your local time when it is different.', yourTime: 'your time', empty: 'No upcoming games yet.' },
  replays: { title: 'Replays', intro: 'Every home game, available within 24 hours.', empty: 'Replays will appear here after the first game.' },
  teams: { title: 'Teams', upcoming: 'Upcoming', results: 'Results and replays', nextPrefix: 'Next', noNext: 'No game scheduled', noResults: 'No results yet.' },
  game: {
    share: 'Share', copied: 'Link copied', addToCalendar: 'Add to calendar', nextUp: 'Next up',
    venue: 'Venue', kickoff: 'Start',
    videoScheduled: 'The stream opens shortly before the start.',
    videoLiveNoStream: 'The stream is starting. This page updates by itself.',
    videoFinalNoReplay: 'The replay will be published within 24 hours of the final whistle.'
  },
  about: {
    title: 'About',
    // DRAFT TEXT - to be confirmed with the school (see docs/OPEN-DECISIONS.md)
    howTitle: 'How to watch',
    how: 'Open the home page. When a game is live you will see "Live now" with a Watch live button. No account or login is needed. Replays are added within 24 hours.',
    whoTitle: 'Who runs the streams',
    who: '[To be confirmed: athletics office and/or student media crew]',
    contactTitle: 'Contact',
    contact: '[Athletics office contact - to be confirmed]',
    privacyTitle: 'Privacy and child safety',
    privacy: 'This site has no accounts, comments or chat. We do not collect personal data about students, and analytics are anonymous. Titles and captions use team names, not student surnames.',
    takedownTitle: 'Request a removal',
    takedown: 'Any family or staff member can ask for a video to be removed. Requests are handled within 24 hours by [named person - to be confirmed].'
  },
  notFound: { title: 'Page not found', loading: 'Loading…', text: 'We could not find that page.', home: 'Back to the home page' },
  admin: {
    title: 'Game admin',
    modePreview: 'Preview mode',
    modeSignedIn: 'Signed in as',
    previewNote: 'Changes are saved only in this browser. Use "Download games.json" to publish them, or connect the database (docs/ADMIN.md) so staff changes go live for everyone.',
    signInTitle: 'Staff sign-in',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signInFailed: 'Could not sign in:',
    add: 'Add game',
    download: 'Download games.json',
    reset: 'Reset draft',
    resetConfirm: 'Discard the changes saved in this browser and go back to the site data?',
    loading: 'Loading games…',
    loadFailed: 'Could not load the games:',
    sections: { live: 'Live now', upcoming: 'Upcoming', finished: 'Finished' },
    none: 'Nothing here yet.',
    edit: 'Edit',
    goLive: 'Go live',
    endGame: 'End game',
    openPage: 'Open game page',
    scoreUp: 'plus one',
    scoreDown: 'minus one',
    noStream: 'No stream link yet',
    noReplay: 'No replay link yet',
    saving: 'Saving…',
    saved: 'Saved',
    saveFailed: 'Could not save:',
    endedHint: 'Game ended. Add the replay link when the video is ready.',
    endedReplayHint: 'Game ended. The live stream is now the replay; paste a different link with Edit if needed.',
    hide: 'Hide from site',
    show: 'Show on site',
    hideConfirm: 'Hide this game from the public site now? Staff can still see it here. To remove the video itself, also make it private on YouTube.',
    hidden: 'Hidden from the public site',
    hiddenHint: 'Hidden. The public site stops showing it right away; shared links stop working after the next rebuild (about 10 minutes).',
    shownHint: 'Showing on the public site again.',
    roleAdmin: 'Admin',
    roleScorer: 'Scorer',
    scorerNote: 'You are signed in as a scorer: you can go live, update scores, end games and set replay links. An admin adds or edits games.',
    notStaff: 'This account is not on the staff list. Ask an admin to add your email, then sign in again.',
    staff: {
      open: 'Staff',
      title: 'Staff',
      intro: 'People on this list can sign in. Admins manage games, takedowns and staff; scorers only run games.',
      email: 'Email',
      role: 'Role',
      add: 'Add to staff',
      you: 'you',
      remove: 'Remove',
      removeConfirm: 'Remove this person from the staff list? They can no longer change anything.',
      makeAdmin: 'Make admin',
      makeScorer: 'Make scorer',
      added: 'Added. They can now set up their account from the sign-in page with “First time here?”.',
      removed: 'Removed from staff.',
      changed: 'Role changed.',
      badEmail: 'Enter a full email address.',
      exists: 'That email is already on the list.',
      back: 'Back to games'
    },
    firstTime: 'First time here? Set up your account',
    setupTitle: 'Set up your staff account',
    setupIntro: 'Use the email an admin added to the staff list and choose a password of at least 8 characters.',
    setupSubmit: 'Create account',
    setupDone: 'Check your email and click the confirmation link, then come back and sign in.',
    setupFailed: 'Could not create the account:',
    setupNotListed: 'This email is not on the staff list yet. Ask an admin to add it first.',
    setupShort: 'Choose a password of at least 8 characters.',
    backToSignIn: 'Back to sign-in',
    liveHint: 'The game is live. Update the score with the buttons.',
    form: {
      newTitle: 'Add a game',
      editTitle: 'Edit game',
      team: 'Sport and level',
      opponent: 'Opponent',
      venue: 'Venue',
      start: 'Start time (Tashkent time)',
      status: 'Status',
      homeScore: 'Owls score',
      awayScore: 'Opponent score',
      stream: 'Live stream link (YouTube)',
      streamHelp: 'Paste the address of the YouTube live stream. Leave empty until it exists.',
      replay: 'Replay link (YouTube)',
      replayHelp: 'Paste the address of the finished video.',
      cover: 'Cover image address (optional)',
      save: 'Save game',
      cancel: 'Cancel',
      remove: 'Delete game',
      removeConfirm: 'Delete this game? This cannot be undone.'
    },
    errors: {
      opponent: 'Enter the opponent name.',
      start: 'Choose the start time.',
      youtube: 'That does not look like a YouTube link.',
      score: 'Scores must be whole numbers from 0 to 999.',
      cover: 'Use a full https:// image address with no spaces or brackets.'
    }
  },
  footer: { school: 'Tashkent International School' }
};
